name = "AxisIndices"
uuid = "f52c9ee2-1b1c-4fd8-8546-6350938c7f11"
authors = ["Tokazama <zchristensen7@gmail.com>"]
version = "0.7.2"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
ChainedFixes = "9706b775-b1f4-4c74-b677-0491368ea71c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
Metadata = "4fb893c1-3164-4f58-823a-cb4c64eabb4f"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticRanges = "d8176aec-3168-11e9-3c98-e3954798be3a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[compat]
AbstractFFTs = "0.5"
ArrayInterface = "2"
ChainedFixes = "0.2"
EllipsisNotation = "0.4"
IntervalSets = "0.4, 0.5"
MappedArrays = "0.3, 0.4"
Metadata = "0.2"
NamedDims = "0.2"
StaticRanges = "0.8"
julia = "1.5"

[extras]
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
