name = "AxisIndices"
uuid = "f52c9ee2-1b1c-4fd8-8546-6350938c7f11"
authors = ["Tokazama <zchristensen7@gmail.com>"]
version = "0.3.11"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
ChainedFixes = "9706b775-b1f4-4c74-b677-0491368ea71c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticRanges = "d8176aec-3168-11e9-3c98-e3954798be3a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArrayInterface = "2"
ChainedFixes = "0.1"
IntervalSets = "0.4, 0.5"
LazyArrays = "0.16"
MappedArrays = "0.2"
NamedDims = "0.2"
PrettyTables = "0.9"
StaticArrays = "0.12"
StaticRanges = "0.6"
julia = "1"

[extras]
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
